AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-egghead-app-example

  Sample SAM Template for sam-egghead-app-example

Globals:
  Function:
    Timeout: 5

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref MyFilesBucket
            Events: s3:ObjectCreated:*
        AddNewItemEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MyAwesomeTable.StreamArn
            StartingPosition: LATEST

  MyFilesBucket:
    Type: AWS::S3::Bucket

  MyAwesomeTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      StreamSpecification:
        StreamViewType: NEW_IMAGES
      PrimaryKey:
        Name: id
        Type: String
      TableName: my-awesome-database

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
